### ISSUE TITLE
servidor de parámetros dinámicos 

### ISSUE THREAD

**Issue by seccortessa** [jmfajardod/param_server_example#1]
Buenas tardes, realizando avances tanto en la tarea que nos dejó como en el taller estaba integrando el tema de parámetros con la herramienta dynamic reconfigure con el controlador.. y tengo un problema específicamente con la parte del servidor...

`from   dynamic_reconfigure.server   import Server
from   kobuki_exer2.cfg             import Kobuki_Exer2Config`

aquí importo los archivos necesarios

específicamente el error me sale en esta parte:

`srv = Server(Kobuki_Exer2Config, self.DynConfCB)`

mi método de callback es el siguiente:

`def DynConfCB(self, config, level):
        self.param = config.angle
        return config`

aquí no estoy muy seguro de la parte de `srv` porque no se utiliza en ninguna otra parte del código..

he de decir que `self.param` está declarada en el init de la siguiente manera:

`self.param = 0.0`

también utilizo esta variable en un callback de suscriptor para realizar la acción de control:

![image](https://user-images.githubusercontent.com/44179423/97119006-70bcc380-16db-11eb-9663-8b1d7e617981.png)

no sé en qué parte podrá estar el error, el cual es el siguiente:

![image](https://user-images.githubusercontent.com/44179423/97119025-8500c080-16db-11eb-981e-8edc0c7cbdb9.png)

Le agradecería mucho su ayuda, espero que tenga un buen día.

**Comment by jmfajardod** [comment]
Buenas tardes, el error es debido a que no se está importando bien el archivo de configuración. Después de definir los parámetros en el archivo **.cfg** es necesario compilar el paquete, le recomiendo revisar que en el archivo **CMakeLists.txt** si ester definida la opción **generate_dynamic_reconfigure_options** y la ubicación del archivo sea correcta. También puede asegurarse de que el parámetro **angle** este definido con ese mismo nombre en el archivo **.cfg**. Quedo pendiente si con eso se resuelve el problema o continua.

**Comment by seccortessa** [comment]
Lo he logrado resolver! tenía razón mi problema era que en el archivo .cfg había quedado con el nombre de **local_param** en vez de **angle** 

Ahora me surge un problema distinto, sucede que yo definí en el **launch** la pose inicial del kobuki como debe ser la del taller `<arg name="yaw" default="$(eval -90 * 3.141592 / 180.0)"/>` y por ejemplo le puse un valor de referencia de **26 grados** para el controlador, pero el ángulo al que el robot se gira es de 26 efectivamente pero desde esa pose inicial, no sé si me explico, no son 26 desde el eje x inercial sino desde donde empieza el kobuki a los -90 grados. Sé que esto hace parte de lo que debo trabajar pero es que el tópico **/odom** me dice que la pose está en 26 grados.

![image](https://user-images.githubusercontent.com/44179423/97119940-9fd63380-16e1-11eb-908f-b6a39708ca31.png)

¿El tópico **/odom** me publica la pose del robot con respecto a su pose inicial y no con respecto al marco inercial?

**Comment by jmfajardod** [comment]
Buenas tardes, si la odometría publica la pose del robot con respecto a la pose inicial no con respecto al marco inercial de Gazebo, esto debido a que si ud lo fuera a implementar en la vida real no hay forma de obtener valores o determinar la posición de un **marco inercial del mundo real**.

**Comment by seccortessa** [comment]
Vale, muchas gracias José!!
